version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile

  photoprocessor:
    image: ${DOCKER_REGISTRY-}photoprocessor
    build:
      context: .
      dockerfile: PhotoProcessor/Dockerfile

